### ISSUE TITLE
Quantitative comparison on Adobe FiveK dataset

### ISSUE THREAD

**Issue by Oktai15** [dros1986/content-preserving-tone-adjustment-for-image-enhancement#1]
Hello, @dros1986! Great work!

I have a question about quantitative comparison on Adobe FiveK dataset. According to your paper: "the dataset is split in 4700 samples for training and two testsets of 50 and 250 samples each". Did you mean that you used 50 samples for validation and 250 for test or something another? Can you provide your list of 250 samples? Maybe you used RANDOM250 from this: https://github.com/Jongchan/DISTORT-AND-RECOVER-CVPR18?

**Comment by dros1986** [comment]
Hi @Oktai15, thank you!

I sent you via email (oktai.tatanov@gmail.com) the version of the dataset we used in this work.

If you have further questions, please let me know.
